gauss_omp: gauss_omp.cpp
	g++ -fopenmp -Wall gauss_omp.cpp -o gauss_omp `pkg-config --cflags --libs opencv`
 
 # g++ `pkg-config opencv --cflags` -O3 -fopenmp -Wall gauss_omp.cpp `pkg-config opencv --libs` -o gauss_omp
 